name: proj_inz
description: "Flutter app for engineering project Coupidyn"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  flutter_svg: ^2.0.7
  provider: ^6.1.5
  url_launcher: ^6.3.2
  icon_decoration: ^2.1.0
  shared_preferences: ^2.5.3
  flutter_markdown: ^0.7.1
  app_settings: ^6.1.1
  path_provider: ^2.1.4
  path: ^1.9.0
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.13.1

  # Bloc
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.2.10

  # Auth
  google_sign_in: ^7.2.0
  flutter_secure_storage: ^8.0.0

  # Stripe
  flutter_dotenv: ^6.0.0
  http: ^1.4.0
  flutter_stripe: ^12.0.2

  # OCR/scanner
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_barcode_scanning: ^0.14.0
  #google_mlkit_text_recognition: ^0.11.0
  #google_mlkit_barcode_scanning: ^0.10.0

  # map
  flutter_map: ^8.2.2
  flutter_map_cache: ^2.0.0
  flutter_map_animations: ^0.9.0
  http_cache_file_store: ^2.0.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/your_background_image.png
    - assets/.env
    - assets/icons/ # to prevent Android crashes remember to ALWAYS use the full local path like this: 'assets/icons/<filename>' 
    - assets/logo/
    - assets/legal/
    - assets/avatars/
  uses-material-design: true
  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/itim/Itim-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-VariableFont_wght.ttf

# to generate icons from assets run `dart run flutter_launcher_icons`
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/app_icon/app_icon.png
  adaptive_icon_foreground: assets/app_icon/app_icon.png
  adaptive_icon_background: "#FFF1D1"
